name: Nightly distribution, 3rd of month
on:
  schedule:
    - cron: '34 4 3 * *'
  workflow_dispatch:

jobs:
  distribution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow_name: [swift-language-git.yml, swift-language-git.yml] 

    steps:
      - uses: actions/checkout@v2
      - run: bash distribute-latest-swift ${{ matrix.workflow_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# vim:set ts=2 sw=2 et:

