name: swift-llvm-git ci

on:
  schedule:
  - cron: "48 23 * * 6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: sccache swift-llvm-git
      uses: actions/cache@v2
      with:
        path: |
          /home/runner/work/swift-aur/swift-aur/swift-llvm-git/src/sccache
          /var/cache/pacman/pkg/
        key: swift-llvm-git-sccache
    - name: build latest runc
      run: |
        sudo apt-get install libseccomp-dev
        git clone https://github.com/opencontainers/runc
        cd runc
        make
        sudo make install
    - name: Build swift-llvm-git AUR
      uses: ProfFan/build-aur-action@0.0.4
      with:
        # AUR repository name to build
        repo-name: swift-llvm-git

    - name: Upload arch pkg
      uses: actions/upload-artifact@v2
      with:
        name: zipped-arch-package
        path: /home/runner/work/swift-aur/swift-aur/swift-llvm-git/*.zst


# vim:set ts=2 sw=2 et:
