name: swift-language-git ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 */3 * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build swift-language-git AUR
      uses: soloturn/build-aur-action@0.0.2
      with:
        # AUR repository name to build
        repo-name: swift-language-git
