name: swift-language sundays

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "23 2 * * 0"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build swift-language
      uses: soloturn/build-aur-action@0.0.2
      with:
        # AUR repository name to build
        repo-name: swift-language
